kind: pipeline
name: default

steps:
- name: build
  image: plugins/hugo
  settings:
    validate: true

- name: deploy
  image: drillster/drone-rsync
  environment:
    RSYNC_KEY:
      from_secret: rsync_key
  settings:
    user: flxptrs
    hosts:
      - machholz.uberspace.de
    source: ./public/
    target: /var/www/virtual/flxptrs/html
    secrets: [ rsync_key ]
    delete: true

trigger:
  branch:
  - master