kind: pipeline
name: default

steps:
- name: build
  image: plugins/hugo
  settings:
    validate: true

- name: deploy
  image: drillster/drone-rsync
  environment:
    RSYNC_KEY:
      from_secret: rsync_key
  settings:
    user: fpeters
    hosts:
      - enif.uberspace.de
    source: ./public/
    target: /home/fpeters/html
    secrets: [ rsync_key ]
    delete: true