name: Deploy

on:
  push:
    branches:
    - gh-actions

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2.4.4
    - name: Build
      run: hugo --minify
    - name: debug
      run: echo ${{secrets.FOO}}
    - name: Rsync to Uberspace
      id: deploy
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
      with:
        flags: '-avzr --delete'
        src: "public/"
        dest: flxptrs@machholz.uberspace.de:/var/www/virtual/flxptrs/html
        
    - name: Display status from deploy
      run: echo "${{ steps.deploy.outputs.status }}"
