name: Deploy

on:
  push:
    branches:
    - gh-actions

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2.4.4
      
    - name: Build
      run: hugo --minify
      
    - name: Setup SSH agent
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY_UBERSPACE }}
      run: |
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${DEPLOY_KEY}"
        ssh flxptrs@machholz.uberspace.de -o 'StrictHostKeychecking no' -C 'pwd; whoami'
